[workspace]
members = [
    "compare_with_wildcard",
    "composition_processor",
    "dictionary_parser",
    "globals",
    "ime",
    "itf_components",
    "numberkey_windows",
    "ruststringrange"
]
